"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "uz" | "en" | "ru" | "kz" | "kg" | "tj"

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

// Simple translations
const translations: Record<Language, Record<string, string>> = {
  uz: {
    dashboard: "Boshqaruv paneli",
    users: "Foydalanuvchilar",
    payments: "To'lovlar Tarixi",
    withdrawals: "Yechib olish arizalari",
    tariffs: "Tariflar",
    statistics: "Statistika",
    notifications: "Bildirishnomalar",
    settings: "Sozlamalar",
    logout: "Chiqish",
    search: "Qidirish...",
    darkMode: "Qorong'i rejim",
    lightMode: "Yorug' rejim",
    export: "Export",
    add: "Qo'shish",
    edit: "Tahrirlash",
    delete: "O'chirish",
    save: "Saqlash",
    cancel: "Bekor qilish",
    confirm: "Tasdiqlash",
    status: "Status",
    active: "Faol",
    inactive: "Nofaol",
    name: "Nomi",
    phone: "Telefon",
    email: "Email",
    price: "Narxi",
    description: "Tavsif",
    features: "Funksiyalar",
    actions: "Amallar",
    date: "Sana",
    amount: "Miqdor",
    balance: "Balans",
    cardNumber: "Karta raqami",
    process: "Jarayon",
    reject: "Rad etish",
    pending: "Kutilmoqda",
    processed: "Bajarildi",
    rejected: "Rad etildi",
    title: "Sarlavha",
    message: "Xabar",
    recipient: "Qabul qiluvchi",
    send: "Yuborish",
    allUsers: "Barcha foydalanuvchilar",
    premiumUsers: "Premium foydalanuvchilar",
    standardUsers: "Standard foydalanuvchilar",
    basicUsers: "Basic foydalanuvchilar",
    general: "Umumiy",
    appearance: "Ko'rinish",
    security: "Xavfsizlik",
    language: "Til",
    dateFormat: "Sana formati",
    emailNotifications: "Email bildirishnomalari",
    smsNotifications: "SMS bildirishnomalari",
    pushNotifications: "Push bildirishnomalari",
    twoFactorAuth: "Ikki faktorli autentifikatsiya",
    sessionTimeout: "Sessiya vaqti tugashi",
    passwordPolicy: "Parol siyosati",
    minLength: "Minimal uzunlik",
    requireUppercase: "Katta harflar talab qilinadi",
    requireNumbers: "Raqamlar talab qilinadi",
    requireSpecialChars: "Maxsus belgilar talab qilinadi",
    siteName: "Sayt nomi",
    siteDescription: "Sayt tavsifi",
    contactEmail: "Aloqa emaili",
    supportPhone: "Qo'llab-quvvatlash telefoni",
    theme: "Mavzu",
    dark: "Qorong'i",
    light: "Yorug'",
    system: "Tizim",
    login: "Kirish",
    password: "Parol",
    forgotPassword: "Parolni unutdingizmi?",
    resetPassword: "Parolni tiklash",
    sendCode: "Kodni yuborish",
    verifyCode: "Kodni tasdiqlash",
    newPassword: "Yangi parol",
    confirmPassword: "Parolni tasdiqlash",
    resetPasswordDescription: "Parolni tiklash uchun telefon raqamingizni kiriting",
    codeVerificationDescription: "Telefon raqamingizga yuborilgan kodni kiriting",
    newPasswordDescription: "Yangi parolingizni kiriting",
    invalidCredentials: "Noto'g'ri email yoki parol",
    invalidCode: "Noto'g'ri kod",
    passwordsDontMatch: "Parollar mos kelmaydi",
    passwordResetSuccess: "Parol muvaffaqiyatli tiklandi",
    loginWithGoogle: "Google orqali kirish",
    or: "Yoki",
    totalUsers: "Jami foydalanuvchilar",
    totalRevenue: "Jami daromad",
    activeTariffs: "Faol tariflar",
    pendingWithdrawals: "Kutilayotgan arizalar",
    recentPayments: "So'nggi to'lovlar",
    newUsers: "Yangi foydalanuvchilar",
    userDetails: "Foydalanuvchi ma'lumotlari",
    tariffDetails: "Tarif ma'lumotlari",
    notificationDetails: "Bildirishnoma ma'lumotlari",
    withdrawalDetails: "Pul yechib olish ma'lumotlari",
    paymentDetails: "To'lov ma'lumotlari",
    overview: "Umumiy ko'rinish",
    analytics: "Analitika",
    userActivity: "Foydalanuvchi faolligi",
    revenueStatistics: "Daromad statistikasi",
    tariffDistribution: "Tarif taqsimoti",
    withdrawalStatistics: "Pul yechib olish statistikasi",
    paymentStatistics: "To'lov statistikasi",
    logins: "Kirishlar",
    transactions: "Tranzaksiyalar",
    downloadPDF: "PDF yuklab olish",
    downloadCSV: "CSV yuklab olish",
    downloadExcel: "Excel yuklab olish",
    print: "Chop etish",
    noDataFound: "Ma'lumot topilmadi",
    loading: "Yuklanmoqda...",
    error: "Xatolik yuz berdi",
    success: "Muvaffaqiyatli",
    warning: "Ogohlantirish",
    info: "Ma'lumot",
    previous: "Oldingi",
    next: "Keyingi",
    page: "Sahifa",
    of: "dan",
    itemsPerPage: "Sahifadagi elementlar soni",
    showingItemsOf: "Ko'rsatilmoqda {start} dan {end} gacha {total} dan",
    filter: "Filtrlash",
    sort: "Saralash",
    ascending: "O'sish bo'yicha",
    descending: "Kamayish bo'yicha",
    clearFilters: "Filtrlarni tozalash",
    applyFilters: "Filtrlarni qo'llash",
    selectAll: "Barchasini tanlash",
    deselectAll: "Barchasini bekor qilish",
    select: "Tanlash",
    selected: "Tanlangan",
    items: "elementlar",
    item: "element",
    noItemsSelected: "Hech qanday element tanlanmagan",
    allItemsSelected: "Barcha elementlar tanlangan",
    search: "Qidirish",
    searchUsers: "Foydalanuvchilarni qidirish...",
    searchPayments: "To'lovlarni qidirish...",
    searchWithdrawals: "Arizalarni qidirish...",
    searchTariffs: "Tariflarni qidirish...",
    searchNotifications: "Bildirishnomalarni qidirish...",
    searchResults: "Qidiruv natijalari",
    noSearchResults: "Qidiruv natijalari topilmadi",
    clearSearch: "Qidiruvni tozalash",
    apply: "Qo'llash",
    reset: "Qayta o'rnatish",
    close: "Yopish",
    open: "Ochish",
    more: "Ko'proq",
    less: "Kamroq",
    all: "Barchasi",
    none: "Hech qanday",
    yes: "Ha",
    no: "Yo'q",
    on: "Yoqilgan",
    off: "O'chirilgan",
    enabled: "Yoqilgan",
    disabled: "O'chirilgan",
    auto: "Avtomatik",
    manual: "Qo'lda",
    default: "Standart",
    custom: "Maxsus",
    basic: "Asosiy",
    advanced: "Kengaytirilgan",
    simple: "Oddiy",
    complex: "Murakkab",
    small: "Kichik",
    medium: "O'rta",
    large: "Katta",
    today: "Bugun",
    yesterday: "Kecha",
    thisWeek: "Shu hafta",
    lastWeek: "O'tgan hafta",
    thisMonth: "Shu oy",
    lastMonth: "O'tgan oy",
    thisYear: "Shu yil",
    lastYear: "O'tgan yil",
    custom: "Maxsus",
    dateRange: "Sana oralig'i",
    startDate: "Boshlanish sanasi",
    endDate: "Tugash sanasi",
    from: "dan",
    to: "gacha",
    apply: "Qo'llash",
    cancel: "Bekor qilish",
    clear: "Tozalash",
    reset: "Qayta o'rnatish",
    save: "Saqlash",
    saveChanges: "O'zgarishlarni saqlash",
    discard: "Bekor qilish",
    discardChanges: "O'zgarishlarni bekor qilish",
    confirmDiscard: "O'zgarishlarni bekor qilishni tasdiqlaysizmi?",
    confirmDelete: "O'chirishni tasdiqlaysizmi?",
    confirmDeleteMessage: "Bu amalni qaytarib bo'lmaydi.",
    confirmAction: "Amalni tasdiqlaysizmi?",
    confirmActionMessage: "Bu amalni qaytarib bo'lmaydi.",
    confirmCancel: "Bekor qilishni tasdiqlaysizmi?",
    confirmCancelMessage: "Barcha o'zgarishlar yo'qoladi.",
    confirmSave: "Saqlashni tasdiqlaysizmi?",
    confirmSaveMessage: "Barcha o'zgarishlar saqlanadi.",
    confirmLogout: "Chiqishni tasdiqlaysizmi?",
    confirmLogoutMessage: "Siz tizimdan chiqmoqchimisiz?",
    confirmReset: "Qayta o'rnatishni tasdiqlaysizmi?",
    confirmResetMessage: "Barcha sozlamalar standart holatga qaytariladi.",
    confirmSubmit: "Yuborishni tasdiqlaysizmi?",
    confirmSubmitMessage: "Ma'lumotlar yuboriladi.",
    confirmClose: "Yopishni tasdiqlaysizmi?",
    confirmCloseMessage: "Barcha o'zgarishlar yo'qoladi.",
    confirmExit: "Chiqishni tasdiqlaysizmi?",
    confirmExitMessage: "Barcha o'zgarishlar yo'qoladi.",
    confirmLeave: "Chiqishni tasdiqlaysizmi?",
    confirmLeaveMessage: "Barcha o'zgarishlar yo'qoladi.",
    view: "Ko'rish",
    back: "Orqaga",
    backToUsers: "Foydalanuvchilarga qaytish",
    userNotFound: "Foydalanuvchi topilmadi",
    userNotFoundDescription: "Ushbu ID bilan foydalanuvchi topilmadi",
    exportUserData: "Foydalanuvchi ma'lumotlarini eksport qilish",
    activitySummary: "Faollik xulosasi",
    activitySummaryDescription: "Foydalanuvchining faollik xulosasi",
    lastLogin: "So'nggi kirish",
    totalLogins: "Jami kirishlar",
    totalPayments: "Jami to'lovlar",
    totalWithdrawals: "Jami yechib olishlar",
    totalSpent: "Jami sarflangan",
    totalWithdrawn: "Jami yechib olingan",
    paymentHistory: "To'lovlar tarixi",
    paymentHistoryDescription: "Foydalanuvchining to'lovlar tarixi",
    withdrawalHistory: "Yechib olishlar tarixi",
    withdrawalHistoryDescription: "Foydalanuvchining yechib olishlar tarixi",
    noPaymentsFound: "To'lovlar topilmadi",
    noWithdrawalsFound: "Yechib olishlar topilmadi",
    id: "ID",
    registrationDate: "Ro'yxatdan o'tgan sana",
    openMenu: "Menyuni ochish",
    generalSettings: "Umumiy sozlamalar",
    appearanceSettings: "Ko'rinish sozlamalari",
    notificationSettings: "Bildirishnoma sozlamalari",
    securitySettings: "Xavfsizlik sozlamalari",
    selectTheme: "Mavzuni tanlang",
    selectLanguage: "Tilni tanlang",
    selectDateFormat: "Sana formatini tanlang",
    usersDescription: "Platformada ro'yxatdan o'tgan barcha foydalanuvchilar ro'yxati",
    allPayments: "Barcha to'lovlar",
    paymentsDescription: "Platformada amalga oshirilgan barcha to'lovlar ro'yxati",
    allWithdrawals: "Barcha arizalar",
    withdrawalsDescription: "Foydalanuvchilar tomonidan yuborilgan pul yechib olish arizalari",
    allTariffs: "Barcha tariflar",
    tariffsDescription: "Platformada mavjud bo'lgan barcha tariflar ro'yxati",
    newNotification: "Yangi bildirishnoma",
    sentNotifications: "Yuborilgan bildirishnomalar",
    notificationTitle: "Bildirishnoma sarlavhasi",
    notificationMessage: "Bildirishnoma matni",
    selectRecipient: "Qabul qiluvchini tanlang",
    recipientDescription: "Bildirishnoma kimga yuborilishini tanlang",
    column: "Ustun",
    markAllAsRead: "Barchasini o'qilgan deb belgilash",
    noNotifications: "Hech qanday bildirishnoma yo'q",
    newNotificationMessage: "Yangi bildirishnoma keldi. Uni tekshirib ko'ring.",
    editUserDescription: "Foydalanuvchi ma'lumotlarini tahrirlash",
    selectTariff: "Tarifni tanlang",
    deactivate: "Nofaol qilish",
    activate: "Faol qilish",
    comparedToLastMonth: "o'tgan oyga nisbatan",
    allTime: "Barcha vaqt davomida",
    currentlyActiveTariffs: "Hozirda faol tariflar",
    withdrawalRequests: "Pul yechib olish uchun arizalar",
    userActivityDescription: "Foydalanuvchi faolligi haqida ma'lumot",
    paymentStatisticsDescription: "To'lovlar statistikasi haqida ma'lumot",
    withdrawalStatisticsDescription: "Pul yechib olish statistikasi haqida ma'lumot",
    analyticsNotAvailable: "Analitika ma'lumotlari hali mavjud emas",
    profile: "Profil",
    profileInformation: "Profil ma'lumotlari",
    updateYourProfileInformation: "Profil ma'lumotlaringizni yangilang",
    changePassword: "Parolni o'zgartirish",
    updateYourPassword: "Parolingizni yangilang",
    currentPassword: "Joriy parol",
    profileUpdated: "Profil yangilandi",
    profileUpdatedDescription: "Profil ma'lumotlaringiz muvaffaqiyatli yangilandi",
    passwordUpdated: "Parol yangilandi",
    passwordUpdatedDescription: "Parolingiz muvaffaqiyatli yangilandi",
  },
  en: {
    dashboard: "Dashboard",
    users: "Users",
    payments: "Payments",
    withdrawals: "Withdrawals",
    tariffs: "Tariffs",
    statistics: "Statistics",
    notifications: "Notifications",
    settings: "Settings",
    logout: "Logout",
    search: "Search...",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    export: "Export",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    name: "Name",
    phone: "Phone",
    email: "Email",
    price: "Price",
    description: "Description",
    features: "Features",
    actions: "Actions",
    date: "Date",
    amount: "Amount",
    balance: "Balance",
    cardNumber: "Card Number",
    process: "Process",
    reject: "Reject",
    pending: "Pending",
    processed: "Processed",
    rejected: "Rejected",
    title: "Title",
    message: "Message",
    recipient: "Recipient",
    send: "Send",
    allUsers: "All Users",
    premiumUsers: "Premium Users",
    standardUsers: "Standard Users",
    basicUsers: "Basic Users",
    general: "General",
    appearance: "Appearance",
    security: "Security",
    language: "Language",
    dateFormat: "Date Format",
    emailNotifications: "Email Notifications",
    smsNotifications: "SMS Notifications",
    pushNotifications: "Push Notifications",
    twoFactorAuth: "Two-Factor Authentication",
    sessionTimeout: "Session Timeout",
    passwordPolicy: "Password Policy",
    minLength: "Minimum Length",
    requireUppercase: "Require Uppercase",
    requireNumbers: "Require Numbers",
    requireSpecialChars: "Require Special Characters",
    siteName: "Site Name",
    siteDescription: "Site Description",
    contactEmail: "Contact Email",
    supportPhone: "Support Phone",
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    system: "System",
    login: "Login",
    password: "Password",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    sendCode: "Send Code",
    verifyCode: "Verify Code",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    resetPasswordDescription: "Enter your phone number to reset your password",
    codeVerificationDescription: "Enter the code sent to your phone",
    newPasswordDescription: "Enter your new password",
    invalidCredentials: "Invalid email or password",
    invalidCode: "Invalid code",
    passwordsDontMatch: "Passwords don't match",
    passwordResetSuccess: "Password reset successfully",
    loginWithGoogle: "Login with Google",
    or: "Or",
    totalUsers: "Total Users",
    totalRevenue: "Total Revenue",
    activeTariffs: "Active Tariffs",
    pendingWithdrawals: "Pending Withdrawals",
    recentPayments: "Recent Payments",
    newUsers: "New Users",
    userDetails: "User Details",
    tariffDetails: "Tariff Details",
    notificationDetails: "Notification Details",
    withdrawalDetails: "Withdrawal Details",
    paymentDetails: "Payment Details",
    overview: "Overview",
    analytics: "Analytics",
    userActivity: "User Activity",
    revenueStatistics: "Revenue Statistics",
    tariffDistribution: "Tariff Distribution",
    withdrawalStatistics: "Withdrawal Statistics",
    paymentStatistics: "Payment Statistics",
    logins: "Logins",
    transactions: "Transactions",
    downloadPDF: "Download PDF",
    downloadCSV: "Download CSV",
    downloadExcel: "Download Excel",
    print: "Print",
    noDataFound: "No data found",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    itemsPerPage: "Items per page",
    showingItemsOf: "Showing {start} to {end} of {total} items",
    filter: "Filter",
    sort: "Sort",
    ascending: "Ascending",
    descending: "Descending",
    clearFilters: "Clear Filters",
    applyFilters: "Apply Filters",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    select: "Select",
    selected: "Selected",
    items: "items",
    item: "item",
    noItemsSelected: "No items selected",
    allItemsSelected: "All items selected",
    search: "Search",
    searchUsers: "Search users...",
    searchPayments: "Search payments...",
    searchWithdrawals: "Search withdrawals...",
    searchTariffs: "Search tariffs...",
    searchNotifications: "Search notifications...",
    searchResults: "Search Results",
    noSearchResults: "No search results found",
    clearSearch: "Clear Search",
    apply: "Apply",
    reset: "Reset",
    close: "Close",
    open: "Open",
    more: "More",
    less: "Less",
    all: "All",
    none: "None",
    yes: "Yes",
    no: "No",
    on: "On",
    off: "Off",
    enabled: "Enabled",
    disabled: "Disabled",
    auto: "Auto",
    manual: "Manual",
    default: "Default",
    custom: "Custom",
    basic: "Basic",
    advanced: "Advanced",
    simple: "Simple",
    complex: "Complex",
    small: "Small",
    medium: "Medium",
    large: "Large",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    lastYear: "Last Year",
    custom: "Custom",
    dateRange: "Date Range",
    startDate: "Start Date",
    endDate: "End Date",
    from: "From",
    to: "To",
    apply: "Apply",
    cancel: "Cancel",
    clear: "Clear",
    reset: "Reset",
    save: "Save",
    saveChanges: "Save Changes",
    discard: "Discard",
    discardChanges: "Discard Changes",
    confirmDiscard: "Are you sure you want to discard changes?",
    confirmDelete: "Are you sure you want to delete?",
    confirmDeleteMessage: "This action cannot be undone.",
    confirmAction: "Are you sure you want to perform this action?",
    confirmActionMessage: "This action cannot be undone.",
    confirmCancel: "Are you sure you want to cancel?",
    confirmCancelMessage: "All changes will be lost.",
    confirmSave: "Are you sure you want to save?",
    confirmSaveMessage: "All changes will be saved.",
    confirmLogout: "Are you sure you want to logout?",
    confirmLogoutMessage: "You will be logged out of the system.",
    confirmReset: "Are you sure you want to reset?",
    confirmResetMessage: "All settings will be reset to default.",
    confirmSubmit: "Are you sure you want to submit?",
    confirmSubmitMessage: "The data will be submitted.",
    confirmClose: "Are you sure you want to close?",
    confirmCloseMessage: "All changes will be lost.",
    confirmExit: "Are you sure you want to exit?",
    confirmExitMessage: "All changes will be lost.",
    confirmLeave: "Are you sure you want to leave?",
    confirmLeaveMessage: "All changes will be lost.",
    view: "View",
    back: "Back",
    backToUsers: "Back to Users",
    userNotFound: "User not found",
    userNotFoundDescription: "The user with this ID was not found",
    exportUserData: "Export User Data",
    activitySummary: "Activity Summary",
    activitySummaryDescription: "Summary of user activity",
    lastLogin: "Last Login",
    totalLogins: "Total Logins",
    totalPayments: "Total Payments",
    totalWithdrawals: "Total Withdrawals",
    totalSpent: "Total Spent",
    totalWithdrawn: "Total Withdrawn",
    paymentHistory: "Payment History",
    paymentHistoryDescription: "User's payment history",
    withdrawalHistory: "Withdrawal History",
    withdrawalHistoryDescription: "User's withdrawal history",
    noPaymentsFound: "No payments found",
    noWithdrawalsFound: "No withdrawals found",
    id: "ID",
    registrationDate: "Registration Date",
    openMenu: "Open Menu",
    generalSettings: "General Settings",
    appearanceSettings: "Appearance Settings",
    notificationSettings: "Notification Settings",
    securitySettings: "Security Settings",
    selectTheme: "Select Theme",
    selectLanguage: "Select Language",
    selectDateFormat: "Select Date Format",
    usersDescription: "List of all registered users on the platform",
    allPayments: "All Payments",
    paymentsDescription: "List of all payments made on the platform",
    allWithdrawals: "All Withdrawals",
    withdrawalsDescription: "Withdrawal requests submitted by users",
    allTariffs: "All Tariffs",
    tariffsDescription: "List of all available tariffs on the platform",
    newNotification: "New Notification",
    sentNotifications: "Sent Notifications",
    notificationTitle: "Notification Title",
    notificationMessage: "Notification Message",
    selectRecipient: "Select Recipient",
    recipientDescription: "Select who will receive the notification",
    column: "Column",
    markAllAsRead: "Mark all as read",
    noNotifications: "No notifications",
    newNotificationMessage: "You have a new notification. Check it out.",
    editUserDescription: "Edit user details",
    selectTariff: "Select tariff",
    deactivate: "Deactivate",
    activate: "Activate",
    comparedToLastMonth: "compared to last month",
    allTime: "All time",
    currentlyActiveTariffs: "Currently active tariffs",
    withdrawalRequests: "Withdrawal requests",
    userActivityDescription: "Information about user activity",
    paymentStatisticsDescription: "Information about payment statistics",
    withdrawalStatisticsDescription: "Information about withdrawal statistics",
    analyticsNotAvailable: "Analytics data is not available yet",
    profile: "Profile",
    profileInformation: "Profile Information",
    updateYourProfileInformation: "Update your profile information",
    changePassword: "Change Password",
    updateYourPassword: "Update your password",
    currentPassword: "Current Password",
    profileUpdated: "Profile Updated",
    profileUpdatedDescription: "Your profile information has been updated successfully",
    passwordUpdated: "Password Updated",
    passwordUpdatedDescription: "Your password has been updated successfully",
  },
  ru: {
    dashboard: "Панель управления",
    users: "Пользователи",
    payments: "Платежи",
    withdrawals: "Выводы",
    tariffs: "Тарифы",
    statistics: "Статистика",
    notifications: "Уведомления",
    settings: "Настройки",
    logout: "Выход",
    search: "Поиск...",
    darkMode: "Темный режим",
    lightMode: "Светлый режим",
    export: "Экспорт",
    add: "Добавить",
    edit: "Редактировать",
    delete: "Удалить",
    save: "Сохранить",
    cancel: "Отмена",
    confirm: "Подтвердить",
    status: "Статус",
    active: "Активный",
    inactive: "Неактивный",
    name: "Имя",
    phone: "Телефон",
    email: "Email",
    price: "Цена",
    description: "Описание",
    features: "Функции",
    actions: "Действия",
    date: "Дата",
    amount: "Сумма",
    balance: "Баланс",
    cardNumber: "Номер карты",
    process: "Обработать",
    reject: "Отклонить",
    pending: "В ожидании",
    processed: "Обработано",
    rejected: "Отклонено",
    title: "Заголовок",
    message: "Сообщение",
    recipient: "Получатель",
    send: "Отправить",
    allUsers: "Все пользователи",
    premiumUsers: "Премиум пользователи",
    standardUsers: "Стандартные пользователи",
    basicUsers: "Базовые пользователи",
    general: "Общие",
    appearance: "Внешний вид",
    security: "Безопасность",
    language: "Язык",
    dateFormat: "Формат даты",
    emailNotifications: "Email уведомления",
    smsNotifications: "SMS уведомления",
    pushNotifications: "Push уведомления",
    twoFactorAuth: "Двухфакторная аутентификация",
    sessionTimeout: "Тайм-аут сессии",
    passwordPolicy: "Политика паролей",
    minLength: "Минимальная длина",
    requireUppercase: "Требовать заглавные буквы",
    requireNumbers: "Требовать цифры",
    requireSpecialChars: "Требовать специальные символы",
    siteName: "Название сайта",
    siteDescription: "Описание сайта",
    contactEmail: "Контактный email",
    supportPhone: "Телефон поддержки",
    theme: "Тема",
    dark: "Темная",
    light: "Светлая",
    system: "Системная",
    login: "Вход",
    password: "Пароль",
    forgotPassword: "Забыли пароль?",
    resetPassword: "Сбросить пароль",
    sendCode: "Отправить код",
    verifyCode: "Проверить код",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердить пароль",
    resetPasswordDescription: "Введите свой номер телефона для сброса пароля",
    codeVerificationDescription: "Введите код, отправленный на ваш телефон",
    newPasswordDescription: "Введите новый пароль",
    invalidCredentials: "Неверный email или пароль",
    invalidCode: "Неверный код",
    passwordsDontMatch: "Пароли не совпадают",
    passwordResetSuccess: "Пароль успешно сброшен",
    loginWithGoogle: "Войти через Google",
    or: "Или",
    totalUsers: "Всего пользователей",
    totalRevenue: "Общий доход",
    activeTariffs: "Активные тарифы",
    pendingWithdrawals: "Ожидающие выводы",
    recentPayments: "Последние платежи",
    newUsers: "Новые пользователи",
    userDetails: "Детали пользователя",
    tariffDetails: "Детали тарифа",
    notificationDetails: "Детали уведомления",
    withdrawalDetails: "Детали вывода",
    paymentDetails: "Детали платежа",
    overview: "Обзор",
    analytics: "Аналитика",
    userActivity: "Активность пользователей",
    revenueStatistics: "Статистика доходов",
    tariffDistribution: "Распределение тарифов",
    withdrawalStatistics: "Статистика выводов",
    paymentStatistics: "Статистика платежей",
    logins: "Входы",
    transactions: "Транзакции",
    downloadPDF: "Скачать PDF",
    downloadCSV: "Скачать CSV",
    downloadExcel: "Скачать Excel",
    print: "Печать",
    noDataFound: "Данные не найдены",
    loading: "Загрузка...",
    error: "Ошибка",
    success: "Успех",
    warning: "Предупреждение",
    info: "Информация",
    previous: "Предыдущий",
    next: "Следующий",
    page: "Страница",
    of: "из",
    itemsPerPage: "Элементов на странице",
    showingItemsOf: "Показано с {start} по {end} из {total} элементов",
    filter: "Фильтр",
    sort: "Сортировка",
    ascending: "По возрастанию",
    descending: "По убыванию",
    clearFilters: "Очистить фильтры",
    applyFilters: "Применить фильтры",
    selectAll: "Выбрать все",
    deselectAll: "Отменить выбор всех",
    select: "Выбрать",
    selected: "Выбрано",
    items: "элементов",
    item: "элемент",
    noItemsSelected: "Нет выбранных элементов",
    allItemsSelected: "Все элементы выбраны",
    search: "Поиск",
    searchUsers: "Поиск пользователей...",
    searchPayments: "Поиск платежей...",
    searchWithdrawals: "Поиск выводов...",
    searchTariffs: "Поиск тарифов...",
    searchNotifications: "Поиск уведомлений...",
    searchResults: "Результаты поиска",
    noSearchResults: "Результаты поиска не найдены",
    clearSearch: "Очистить поиск",
    apply: "Применить",
    reset: "Сбросить",
    close: "Закрыть",
    open: "Открыть",
    more: "Больше",
    less: "Меньше",
    all: "Все",
    none: "Нет",
    yes: "Да",
    no: "Нет",
    on: "Вкл",
    off: "Выкл",
    enabled: "Включено",
    disabled: "Отключено",
    auto: "Авто",
    manual: "Вручную",
    default: "По умолчанию",
    custom: "Пользовательский",
    basic: "Базовый",
    advanced: "Расширенный",
    simple: "Простой",
    complex: "Сложный",
    small: "Маленький",
    medium: "Средний",
    large: "Большой",
    usersDescription: "Список всех зарегистрированных пользователей на платформе",
    allPayments: "Все платежи",
    paymentsDescription: "Список всех платежей, совершенных на платформе",
    allWithdrawals: "Все выводы",
    withdrawalsDescription: "Заявки на вывод средств, отправленные пользователями",
    allTariffs: "Все тарифы",
    tariffsDescription: "Список всех доступных тарифов на платформе",
    newNotification: "Новое уведомление",
    sentNotifications: "Отправленные уведомления",
    notificationTitle: "Заголовок уведомления",
    notificationMessage: "Сообщение уведомления",
    selectRecipient: "Выберите получателя",
    recipientDescription: "Выберите, кто получит уведомление",
    column: "Колонка",
    markAllAsRead: "Отметить все как прочитанные",
    noNotifications: "Нет уведомлений",
    newNotificationMessage: "У вас новое уведомление. Проверьте его.",
    editUserDescription: "Редактировать данные пользователя",
    selectTariff: "Выберите тариф",
    deactivate: "Деактивировать",
    activate: "Активировать",
    comparedToLastMonth: "по сравнению с прошлым месяцем",
    allTime: "За все время",
    currentlyActiveTariffs: "Текущие активные тарифы",
    withdrawalRequests: "Запросы на вывод",
    userActivityDescription: "Информация об активности пользователей",
    paymentStatisticsDescription: "Информация о статистике платежей",
    withdrawalStatisticsDescription: "Информация о статистике выводов",
    analyticsNotAvailable: "Аналитические данные пока недоступны",
    profile: "Профиль",
    profileInformation: "Информация профиля",
    updateYourProfileInformation: "Обновите информацию вашего профиля",
    changePassword: "Изменить пароль",
    updateYourPassword: "Обновите ваш пароль",
    currentPassword: "Текущий пароль",
    profileUpdated: "Профиль обновлен",
    profileUpdatedDescription: "Информация вашего профиля успешно обновлена",
    passwordUpdated: "Пароль обновлен",
    passwordUpdatedDescription: "Ваш пароль успешно обновлен",
  },
  kz: {
    dashboard: "Басқару тақтасы",
    users: "Пайдаланушылар",
    payments: "Төлемдер",
    withdrawals: "Ақша шығару",
    tariffs: "Тарифтер",
    statistics: "Статистика",
    notifications: "Хабарламалар",
    settings: "Параметрлер",
    logout: "Шығу",
    search: "Іздеу...",
    // Basic translations for Kazakh - would need to be expanded
    column: "Баған",
  },
  kg: {
    dashboard: "Башкаруу панели",
    users: "Колдонуучулар",
    payments: "Төлөмдөр",
    withdrawals: "Акча чыгаруу",
    tariffs: "Тарифтер",
    statistics: "Статистика",
    notifications: "Билдирүүлөр",
    settings: "Параметрлер",
    logout: "Чыгуу",
    search: "Издөө...",
    // Basic translations for Kyrgyz - would need to be expanded
    column: "Мамыча",
  },
  tj: {
    dashboard: "Лавҳаи идоракунӣ",
    users: "Корбарон",
    payments: "Пардохтҳо",
    withdrawals: "Гирифтани пул",
    tariffs: "Тарифҳо",
    statistics: "Омор",
    notifications: "Огоҳиномаҳо",
    settings: "Танзимот",
    logout: "Баромадан",
    search: "Ҷустуҷӯ...",
    // Basic translations for Tajik - would need to be expanded
    column: "Сутун",
  },
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>("uz")

  useEffect(() => {
    // Load language from localStorage if available
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }

    // Set up event listener for language changes in other tabs
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === "language" && e.newValue && Object.keys(translations).includes(e.newValue as Language)) {
        setLanguage(e.newValue as Language)
      }
    }

    window.addEventListener("storage", handleStorageChange)
    return () => window.removeEventListener("storage", handleStorageChange)
  }, [])

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
  }

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
