"use client";

import type React from "react";
import { createContext, useContext, useState, useEffect } from "react";

type Language = "uz" | "en" | "ru" | "kz" | "kg" | "tj";

type LanguageContextType = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Simple translations
const translations: Record<Language, Record<string, string>> = {
  uz: {
    dashboard: "Boshqaruv paneli",
    users: "Foydalanuvchilar",
    payments: "To'lovlar Tarixi",
    withdrawals: "Yechib olish arizalari",
    tariffs: "Tariflar",
    statistics: "Statistika",
    notifications: "Bildirishnomalar",
    settings: "Sozlamalar",
    logout: "Chiqish",
    search: "Qidirish...",
    darkMode: "Qorong'i rejim",
    lightMode: "Yorug' rejim",
    export: "Export",
    add: "Qo'shish",
    edit: "Tahrirlash",
    delete: "O'chirish",
    save: "Saqlash",
    cancel: "Bekor qilish",
    confirm: "Tasdiqlash",
    status: "Status",
    active: "Faol",
    inactive: "Nofaol",
    name: "Nomi",
    phone: "Telefon",
    email: "Email",
    price: "Narxi",
    description: "Tavsif",
    features: "Funksiyalar",
    actions: "Amallar",
    date: "Sana",
    amount: "Miqdor",
    balance: "Balans",
    cardNumber: "Karta raqami",
    process: "Jarayon",
    reject: "Rad etish",
    pending: "Kutilmoqda",
    processed: "Bajarildi",
    rejected: "Rad etildi",
    title: "Sarlavha",
    message: "Xabar",
    recipient: "Qabul qiluvchi",
    send: "Yuborish",
    allUsers: "Barcha foydalanuvchilar",
    premiumUsers: "Premium foydalanuvchilar",
    standardUsers: "Standard foydalanuvchilar",
    basicUsers: "Basic foydalanuvchilar",
    general: "Umumiy",
    appearance: "Ko'rinish",
    security: "Xavfsizlik",
    language: "Til",
    dateFormat: "Sana formati",
    emailNotifications: "Email bildirishnomalari",
    smsNotifications: "SMS bildirishnomalari",
    pushNotifications: "Push bildirishnomalari",
    twoFactorAuth: "Ikki faktorli autentifikatsiya",
    sessionTimeout: "Sessiya vaqti tugashi",
    passwordPolicy: "Parol siyosati",
    minLength: "Minimal uzunlik",
    requireUppercase: "Katta harflar talab qilinadi",
    requireNumbers: "Raqamlar talab qilinadi",
    requireSpecialChars: "Maxsus belgilar talab qilinadi",
    siteName: "Sayt nomi",
    siteDescription: "Sayt tavsifi",
    contactEmail: "Aloqa emaili",
    supportPhone: "Qo'llab-quvvatlash telefoni",
    theme: "Mavzu",
    dark: "Qorong'i",
    light: "Yorug'",
    system: "Tizim",
    login: "Kirish",
    password: "Parol",
    forgotPassword: "Parolni unutdingizmi?",
    resetPassword: "Parolni tiklash",
    sendCode: "Kodni yuborish",
    verifyCode: "Kodni tasdiqlash",
    newPassword: "Yangi parol",
    confirmPassword: "Parolni tasdiqlash",
    resetPasswordDescription:
      "Parolni tiklash uchun telefon raqamingizni kiriting",
    codeVerificationDescription:
      "Telefon raqamingizga yuborilgan kodni kiriting",
    newPasswordDescription: "Yangi parolingizni kiriting",
    invalidCredentials: "Noto'g'ri email yoki parol",
    invalidCode: "Noto'g'ri kod",
    passwordsDontMatch: "Parollar mos kelmaydi",
    passwordResetSuccess: "Parol muvaffaqiyatli tiklandi",
    loginWithGoogle: "Google orqali kirish",
    or: "Yoki",
    totalUsers: "Jami foydalanuvchilar",
    totalRevenue: "Jami daromad",
    activeTariffs: "Faol tariflar",
    pendingWithdrawals: "Kutilayotgan arizalar",
    recentPayments: "So'nggi to'lovlar",
    newUsers: "Yangi foydalanuvchilar",
    userDetails: "Foydalanuvchi ma'lumotlari",
    tariffDetails: "Tarif ma'lumotlari",
    notificationDetails: "Bildirishnoma ma'lumotlari",
    withdrawalDetails: "Pul yechib olish ma'lumotlari",
    paymentDetails: "To'lov ma'lumotlari",
    overview: "Umumiy ko'rinish",
    analytics: "Analitika",
    userActivity: "Foydalanuvchi faolligi",
    revenueStatistics: "Daromad statistikasi",
    tariffDistribution: "Tarif taqsimoti",
    withdrawalStatistics: "Pul yechib olish statistikasi",
    paymentStatistics: "To'lov statistikasi",
    logins: "Kirishlar",
    transactions: "Tranzaksiyalar",
    downloadPDF: "PDF yuklab olish",
    downloadCSV: "CSV yuklab olish",
    downloadExcel: "Excel yuklab olish",
    print: "Chop etish",
    noDataFound: "Ma'lumot topilmadi",
    loading: "Yuklanmoqda...",
    error: "Xatolik yuz berdi",
    success: "Muvaffaqiyatli",
    warning: "Ogohlantirish",
    info: "Ma'lumot",
    previous: "Oldingi",
    next: "Keyingi",
    page: "Sahifa",
    of: "dan",
    itemsPerPage: "Sahifadagi elementlar soni",
    showingItemsOf: "Ko'rsatilmoqda {start} dan {end} gacha {total} dan",
    filter: "Filtrlash",
    sort: "Saralash",
    ascending: "O'sish bo'yicha",
    descending: "Kamayish bo'yicha",
    clearFilters: "Filtrlarni tozalash",
    applyFilters: "Filtrlarni qo'llash",
    selectAll: "Barchasini tanlash",
    deselectAll: "Barchasini bekor qilish",
    select: "Tanlash",
    selected: "Tanlangan",
    items: "elementlar",
    item: "element",
    noItemsSelected: "Hech qanday element tanlanmagan",
    allItemsSelected: "Barcha elementlar tanlangan",
    searchUsers: "Foydalanuvchilarni qidirish...",
    searchPayments: "To'lovlarni qidirish...",
    searchWithdrawals: "Arizalarni qidirish...",
    searchTariffs: "Tariflarni qidirish...",
    searchNotifications: "Bildirishnomalarni qidirish...",
    searchResults: "Qidiruv natijalari",
    noSearchResults: "Qidiruv natijalari topilmadi",
    clearSearch: "Qidiruvni tozalash",
    apply: "Qo'llash",
    reset: "Qayta o'rnatish",
    close: "Yopish",
    open: "Ochish",
    more: "Ko'proq",
    less: "Kamroq",
    all: "Barchasi",
    none: "Hech qanday",
    yes: "Ha",
    no: "Yo'q",
    on: "Yoqilgan",
    off: "O'chirilgan",
    enabled: "Yoqilgan",
    disabled: "O'chirilgan",
    auto: "Avtomatik",
    manual: "Qo'lda",
    default: "Standart",
    custom: "Maxsus",
    basic: "Asosiy",
    advanced: "Kengaytirilgan",
    simple: "Oddiy",
    complex: "Murakkab",
    small: "Kichik",
    medium: "O'rta",
    large: "Katta",
    today: "Bugun",
    yesterday: "Kecha",
    thisWeek: "Shu hafta",
    lastWeek: "O'tgan hafta",
    thisMonth: "Shu oy",
    lastMonth: "O'tgan oy",
    thisYear: "Shu yil",
    lastYear: "O'tgan yil",
    dateRange: "Sana oralig'i",
    startDate: "Boshlanish sanasi",
    endDate: "Tugash sanasi",
    from: "dan",
    to: "gacha",
    clear: "Tozalash",
    saveChanges: "O'zgarishlarni saqlash",
    discard: "Bekor qilish",
    discardChanges: "O'zgarishlarni bekor qilish",
    confirmDiscard: "O'zgarishlarni bekor qilishni tasdiqlaysizmi?",
    confirmDelete: "O'chirishni tasdiqlaysizmi?",
    confirmDeleteMessage: "Bu amalni qaytarib bo'lmaydi.",
    confirmAction: "Amalni tasdiqlaysizmi?",
    confirmActionMessage: "Bu amalni qaytarib bo'lmaydi.",
    confirmCancel: "Bekor qilishni tasdiqlaysizmi?",
    confirmCancelMessage: "Barcha o'zgarishlar yo'qoladi.",
    confirmSave: "Saqlashni tasdiqlaysizmi?",
    confirmSaveMessage: "Barcha o'zgarishlar saqlanadi.",
    confirmLogout: "Chiqishni tasdiqlaysizmi?",
    confirmLogoutMessage: "Siz tizimdan chiqmoqchimisiz?",
    confirmReset: "Qayta o'rnatishni tasdiqlaysizmi?",
    confirmResetMessage: "Barcha sozlamalar standart holatga qaytariladi.",
    confirmSubmit: "Yuborishni tasdiqlaysizmi?",
    confirmSubmitMessage: "Ma'lumotlar yuboriladi.",
    confirmClose: "Yopishni tasdiqlaysizmi?",
    confirmCloseMessage: "Barcha o'zgarishlar yo'qoladi.",
    confirmExit: "Chiqishni tasdiqlaysizmi?",
    confirmExitMessage: "Barcha o'zgarishlar yo'qoladi.",
    confirmLeave: "Chiqishni tasdiqlaysizmi?",
    confirmLeaveMessage: "Barcha o'zgarishlar yo'qoladi.",
    view: "Ko'rish",
    back: "Orqaga",
    backToUsers: "Foydalanuvchilarga qaytish",
    userNotFound: "Foydalanuvchi topilmadi",
    userNotFoundDescription: "Ushbu ID bilan foydalanuvchi topilmadi",
    exportUserData: "Foydalanuvchi ma'lumotlarini eksport qilish",
    activitySummary: "Faollik xulosasi",
    activitySummaryDescription:
      "Foydalanuvchining so'nggi faolliklari haqida umumiy ma'lumot",
    lastLogin: "So'nggi kirish",
    totalLogins: "Jami kirishlar",
    totalPayments: "Jami to'lovlar",
    totalWithdrawals: "Jami yechib olishlar",
    totalSpent: "Jami sarflangan",
    totalWithdrawn: "Jami yechib olingan",
    paymentHistory: "To'lovlar tarixi",
    paymentHistoryDescription: "Foydalanuvchining to'lovlar tarixi",
    withdrawalHistory: "Yechib olishlar tarixi",
    withdrawalHistoryDescription: "Foydalanuvchining yechib olishlar tarixi",
    noPaymentsFound: "To'lovlar topilmadi",
    noWithdrawalsFound: "Yechib olishlar topilmadi",
    id: "ID",
    registrationDate: "Ro'yxatdan o'tgan sana",
    openMenu: "Menyuni ochish",
    generalSettings: "Umumiy sozlamalar",
    appearanceSettings: "Ko'rinish sozlamalari",
    notificationSettings: "Bildirishnoma sozlamalari",
    securitySettings: "Xavfsizlik sozlamalari",
    selectTheme: "Mavzuni tanlang",
    selectLanguage: "Tilni tanlang",
    selectDateFormat: "Sana formatini tanlang",
    usersDescription:
      "Platformada ro'yxatdan o'tgan barcha foydalanuvchilar ro'yxati",
    allPayments: "Barcha to'lovlar",
    paymentsDescription:
      "Platformada amalga oshirilgan barcha to'lovlar ro'yxati",
    allWithdrawals: "Barcha arizalar",
    withdrawalsDescription:
      "Foydalanuvchilar tomonidan yuborilgan pul yechib olish arizalari",
    allTariffs: "Barcha tariflar",
    tariffsDescription: "Platformada mavjud bo'lgan barcha tariflar ro'yxati",
    newNotification: "Yangi bildirishnoma",
    sentNotifications: "Yuborilgan bildirishnomalar",
    notificationTitle: "Bildirishnoma sarlavhasi",
    notificationMessage: "Bildirishnoma matni",
    selectRecipient: "Qabul qiluvchini tanlang",
    recipientDescription: "Bildirishnoma kimga yuborilishini tanlang",
    column: "Ustun",
    markAllAsRead: "Barchasini o'qilgan deb belgilash",
    noNotifications: "Hech qanday bildirishnoma yo'q",
    newNotificationMessage: "Yangi bildirishnoma keldi. Uni tekshirib ko'ring.",
    editUserDescription: "Foydalanuvchi ma'lumotlarini tahrirlash",
    selectTariff: "Tarifni tanlang",
    deactivate: "Nofaol qilish",
    activate: "Faol qilish",
    comparedToLastMonth: "o'tgan oyga nisbatan",
    allTime: "Barcha vaqt davomida",
    currentlyActiveTariffs: "Hozirda faol tariflar",
    withdrawalRequests: "Pul yechib olish uchun arizalar",
    userActivityDescription: "Foydalanuvchi faolligi haqida ma'lumot",
    paymentStatisticsDescription: "To'lovlar statistikasi haqida ma'lumot",
    withdrawalStatisticsDescription:
      "Pul yechib olish statistikasi haqida ma'lumot",
    analyticsNotAvailable: "Analitika ma'lumotlari hali mavjud emas",
    profile: "Profil",
    profileInformation: "Profil ma'lumotlari",
    updateYourProfileInformation: "Profil ma'lumotlaringizni yangilang",
    changePassword: "Parolni o'zgartirish",
    updateYourPassword: "Parolingizni yangilang",
    currentPassword: "Joriy parol",
    profileUpdated: "Profil yangilandi",
    profileUpdatedDescription:
      "Profil ma'lumotlaringiz muvaffaqiyatli yangilandi",
    passwordUpdated: "Parol yangilandi",
    passwordUpdatedDescription: "Parolingiz muvaffaqiyatli yangilandi",
  },
  en: {
    dashboard: "Dashboard",
    users: "Users",
    payments: "Payments",
    withdrawals: "Withdrawals",
    tariffs: "Tariffs",
    statistics: "Statistics",
    notifications: "Notifications",
    settings: "Settings",
    logout: "Logout",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    export: "Export",
    add: "Add",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    confirm: "Confirm",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    name: "Name",
    phone: "Phone",
    email: "Email",
    price: "Price",
    description: "Description",
    features: "Features",
    actions: "Actions",
    date: "Date",
    amount: "Amount",
    balance: "Balance",
    cardNumber: "Card Number",
    process: "Process",
    reject: "Reject",
    pending: "Pending",
    processed: "Processed",
    rejected: "Rejected",
    title: "Title",
    message: "Message",
    recipient: "Recipient",
    send: "Send",
    allUsers: "All Users",
    premiumUsers: "Premium Users",
    standardUsers: "Standard Users",
    basicUsers: "Basic Users",
    general: "General",
    appearance: "Appearance",
    security: "Security",
    language: "Language",
    dateFormat: "Date Format",
    emailNotifications: "Email Notifications",
    smsNotifications: "SMS Notifications",
    pushNotifications: "Push Notifications",
    twoFactorAuth: "Two-Factor Authentication",
    sessionTimeout: "Session Timeout",
    passwordPolicy: "Password Policy",
    minLength: "Minimum Length",
    requireUppercase: "Require Uppercase",
    requireNumbers: "Require Numbers",
    requireSpecialChars: "Require Special Characters",
    siteName: "Site Name",
    siteDescription: "Site Description",
    contactEmail: "Contact Email",
    supportPhone: "Support Phone",
    theme: "Theme",
    dark: "Dark",
    light: "Light",
    system: "System",
    login: "Login",
    password: "Password",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    sendCode: "Send Code",
    verifyCode: "Verify Code",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    resetPasswordDescription: "Enter your phone number to reset your password",
    codeVerificationDescription: "Enter the code sent to your phone",
    newPasswordDescription: "Enter your new password",
    invalidCredentials: "Invalid email or password",
    invalidCode: "Invalid code",
    passwordsDontMatch: "Passwords don't match",
    passwordResetSuccess: "Password reset successfully",
    loginWithGoogle: "Login with Google",
    or: "Or",
    totalUsers: "Total Users",
    totalRevenue: "Total Revenue",
    activeTariffs: "Active Tariffs",
    pendingWithdrawals: "Pending Withdrawals",
    recentPayments: "Recent Payments",
    newUsers: "New Users",
    userDetails: "User Details",
    tariffDetails: "Tariff Details",
    notificationDetails: "Notification Details",
    withdrawalDetails: "Withdrawal Details",
    paymentDetails: "Payment Details",
    overview: "Overview",
    analytics: "Analytics",
    userActivity: "User Activity",
    revenueStatistics: "Revenue Statistics",
    tariffDistribution: "Tariff Distribution",
    withdrawalStatistics: "Withdrawal Statistics",
    paymentStatistics: "Payment Statistics",
    logins: "Logins",
    transactions: "Transactions",
    downloadPDF: "Download PDF",
    downloadCSV: "Download CSV",
    downloadExcel: "Download Excel",
    print: "Print",
    noDataFound: "No data found",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    warning: "Warning",
    info: "Info",
    previous: "Previous",
    next: "Next",
    page: "Page",
    of: "of",
    itemsPerPage: "Items per page",
    showingItemsOf: "Showing {start} to {end} of {total} items",
    filter: "Filter",
    sort: "Sort",
    ascending: "Ascending",
    descending: "Descending",
    clearFilters: "Clear Filters",
    applyFilters: "Apply Filters",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    select: "Select",
    selected: "Selected",
    items: "Items",
    item: "Item",
    noItemsSelected: "No items selected",
    allItemsSelected: "All items selected",
    search: "Search",
    searchUsers: "Search users...",
    searchPayments: "Search payments...",
    searchWithdrawals: "Search withdrawals...",
    searchTariffs: "Search tariffs...",
    searchNotifications: "Search notifications...",
    searchResults: "Search Results",
    noSearchResults: "No search results found",
    clearSearch: "Clear Search",
    apply: "Apply",
    reset: "Reset",
    close: "Close",
    open: "Open",
    more: "More",
    less: "Less",
    all: "All",
    none: "None",
    yes: "Yes",
    no: "No",
    on: "On",
    off: "Off",
    enabled: "Enabled",
    disabled: "Disabled",
    auto: "Auto",
    manual: "Manual",
    default: "Default",
    custom: "Custom",
    basic: "Basic",
    advanced: "Advanced",
    simple: "Simple",
    complex: "Complex",
    small: "Small",
    medium: "Medium",
    large: "Large",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    lastWeek: "Last Week",
    thisMonth: "This Month",
    lastMonth: "Last Month",
    thisYear: "This Year",
    lastYear: "Last Year",

    dateRange: "Date Range",
    startDate: "Start Date",
    endDate: "End Date",
    from: "From",
    to: "To",
    clear: "Clear",
    saveChanges: "Save Changes",
    discard: "Discard",
    discardChanges: "Discard Changes",
    confirmDiscard: "Are you sure you want to discard changes?",
    confirmDelete: "Are you sure you want to delete?",
    confirmDeleteMessage: "This action cannot be undone.",
    confirmAction: "Are you sure you want to perform this action?",
    confirmActionMessage: "This action cannot be undone.",
    confirmCancel: "Are you sure you want to cancel?",
    confirmCancelMessage: "All changes will be lost.",
    confirmSave: "Are you sure you want to save?",
    confirmSaveMessage: "All changes will be saved.",
    confirmLogout: "Are you sure you want to logout?",
    confirmLogoutMessage: "You will be logged out of the system.",
    confirmReset: "Are you sure you want to reset?",
    confirmResetMessage: "All settings will be reset to default.",
    confirmSubmit: "Are you sure you want to submit?",
    confirmSubmitMessage: "The data will be submitted.",
    confirmClose: "Are you sure you want to close?",
    confirmCloseMessage: "All changes will be lost.",
    confirmExit: "Are you sure you want to exit?",
    confirmExitMessage: "All changes will be lost.",
    confirmLeave: "Are you sure you want to leave?",
    confirmLeaveMessage: "All changes will be lost.",
    view: "View",
    back: "Back",
    backToUsers: "Back to Users",
    userNotFound: "User not found",
    userNotFoundDescription: "The user with this ID was not found",
    exportUserData: "Export User Data",
    activitySummary: "Activity Summary",
    activitySummaryDescription: "Summary of user activity",
    lastLogin: "Last Login",
    totalLogins: "Total Logins",
    totalPayments: "Total Payments",
    totalWithdrawals: "Total Withdrawals",
    totalSpent: "Total Spent",
    totalWithdrawn: "Total Withdrawn",
    paymentHistory: "Payment History",
    paymentHistoryDescription: "User's payment history",
    withdrawalHistory: "Withdrawal History",
    withdrawalHistoryDescription: "User's withdrawal history",
    noPaymentsFound: "No payments found",
    noWithdrawalsFound: "No withdrawals found",
    id: "ID",
    registrationDate: "Registration Date",
    openMenu: "Open Menu",
    generalSettings: "General Settings",
    appearanceSettings: "Appearance Settings",
    notificationSettings: "Notification Settings",
    securitySettings: "Security Settings",
    selectTheme: "Select Theme",
    selectLanguage: "Select Language",
    selectDateFormat: "Select Date Format",
    usersDescription: "List of all registered users on the platform",
    allPayments: "All Payments",
    paymentsDescription: "List of all payments made on the platform",
    allWithdrawals: "All Withdrawals",
    withdrawalsDescription: "Withdrawal requests submitted by users",
    allTariffs: "All Tariffs",
    tariffsDescription: "List of all available tariffs on the platform",
    newNotification: "New Notification",
    sentNotifications: "Sent Notifications",
    notificationTitle: "Notification Title",
    notificationMessage: "Notification Message",
    selectRecipient: "Select Recipient",
    recipientDescription: "Select who will receive the notification",
    column: "Column",
    markAllAsRead: "Mark all as read",
    noNotifications: "No notifications",
    newNotificationMessage: "You have a new notification. Check it out.",
    editUserDescription: "Edit user details",
    selectTariff: "Select tariff",
    deactivate: "Deactivate",
    activate: "Activate",
    comparedToLastMonth: "compared to last month",
    allTime: "All time",
    currentlyActiveTariffs: "Currently active tariffs",
    withdrawalRequests: "Withdrawal requests",
    userActivityDescription: "Information about user activity",
    paymentStatisticsDescription: "Information about payment statistics",
    withdrawalStatisticsDescription: "Information about withdrawal statistics",
    analyticsNotAvailable: "Analytics data is not available yet",
    profile: "Profile",
    profileInformation: "Profile Information",
    updateYourProfileInformation: "Update your profile information",
    changePassword: "Change Password",
    updateYourPassword: "Update your password",
    currentPassword: "Current Password",
    profileUpdated: "Profile Updated",
    profileUpdatedDescription:
      "Your profile information has been updated successfully",
    passwordUpdated: "Password Updated",
    passwordUpdatedDescription: "Your password has been updated successfully",
  },
  ru: {
    dashboard: "Панель управления",
    users: "Пользователи",
    payments: "История платежей",
    withdrawals: "Заявки на вывод",
    tariffs: "Тарифы",
    statistics: "Статистика",
    notifications: "Уведомления",
    settings: "Настройки",
    logout: "Выход",
    search: "Поиск...",
    darkMode: "Темный режим",
    lightMode: "Светлый режим",
    export: "Экспорт",
    add: "Добавить",
    edit: "Редактировать",
    delete: "Удалить",
    save: "Сохранить",
    cancel: "Отмена",
    confirm: "Подтвердить",
    status: "Статус",
    active: "Активный",
    inactive: "Неактивный",
    name: "Имя",
    phone: "Телефон",
    email: "Электронная почта",
    price: "Цена",
    description: "Описание",
    features: "Функции",
    actions: "Действия",
    date: "Дата",
    amount: "Сумма",
    balance: "Баланс",
    cardNumber: "Номер карты",
    process: "Обработка",
    reject: "Отклонить",
    pending: "В ожидании",
    processed: "Обработано",
    rejected: "Отклонено",
    title: "Заголовок",
    message: "Сообщение",
    recipient: "Получатель",
    send: "Отправить",
    allUsers: "Все пользователи",
    premiumUsers: "Премиум пользователи",
    standardUsers: "Стандартные пользователи",
    basicUsers: "Базовые пользователи",
    general: "Общие",
    appearance: "Внешний вид",
    security: "Безопасность",
    language: "Язык",
    dateFormat: "Формат даты",
    emailNotifications: "Уведомления по электронной почте",
    smsNotifications: "SMS-уведомления",
    pushNotifications: "Push-уведомления",
    twoFactorAuth: "Двухфакторная аутентификация",
    sessionTimeout: "Время ожидания сессии",
    passwordPolicy: "Политика паролей",
    minLength: "Минимальная длина",
    requireUppercase: "Требуются заглавные буквы",
    requireNumbers: "Требуются цифры",
    requireSpecialChars: "Требуются специальные символы",
    siteName: "Название сайта",
    siteDescription: "Описание сайта",
    contactEmail: "Контактный email",
    supportPhone: "Телефон поддержки",
    theme: "Тема",
    dark: "Темная",
    light: "Светлая",
    system: "Системная",
    login: "Вход",
    password: "Пароль",
    forgotPassword: "Забыли пароль?",
    resetPassword: "Сброс пароля",
    sendCode: "Отправить код",
    verifyCode: "Подтвердить код",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердите пароль",
    resetPasswordDescription: "Введите ваш номер телефона для сброса пароля",
    codeVerificationDescription:
      "Введите код, отправленный на ваш номер телефона",
    newPasswordDescription: "Введите ваш новый пароль",
    invalidCredentials: "Неверный email или пароль",
    invalidCode: "Неверный код",
    passwordsDontMatch: "Пароли не совпадают",
    passwordResetSuccess: "Пароль успешно сброшен",
    loginWithGoogle: "Войти через Google",
    or: "Или",
    totalUsers: "Всего пользователей",
    totalRevenue: "Общий доход",
    activeTariffs: "Активные тарифы",
    pendingWithdrawals: "Ожидающие заявки",
    recentPayments: "Последние платежи",
    newUsers: "Новые пользователи",
    userDetails: "Информация о пользователе",
    tariffDetails: "Информация о тарифе",
    notificationDetails: "Детали уведомления",
    withdrawalDetails: "Детали вывода средств",
    paymentDetails: "Детали платежа",
    overview: "Обзор",
    analytics: "Аналитика",
    userActivity: "Активность пользователей",
    revenueStatistics: "Статистика доходов",
    tariffDistribution: "Распределение тарифов",
    withdrawalStatistics: "Статистика выводов",
    paymentStatistics: "Статистика платежей",
    logins: "Входы",
    transactions: "Транзакции",
    downloadPDF: "Скачать PDF",
    downloadCSV: "Скачать CSV",
    downloadExcel: "Скачать Excel",
    print: "Печать",
    noDataFound: "Данные не найдены",
    loading: "Загрузка...",
    error: "Произошла ошибка",
    success: "Успешно",
    warning: "Предупреждение",
    info: "Информация",
    previous: "Предыдущая",
    next: "Следующая",
    page: "Страница",
    of: "из",
    itemsPerPage: "Элементов на странице",
    showingItemsOf: "Показаны элементы с {start} по {end} из {total}",
    filter: "Фильтр",
    sort: "Сортировка",
    ascending: "По возрастанию",
    descending: "По убыванию",
    clearFilters: "Сбросить фильтры",
    applyFilters: "Применить фильтры",
    selectAll: "Выбрать все",
    deselectAll: "Снять выбор",
    select: "Выбрать",
    selected: "Выбрано",
    items: "элементы",
    item: "элемент",
    noItemsSelected: "Нет выбранных элементов",
    allItemsSelected: "Все элементы выбраны",
    searchUsers: "Поиск пользователей...",
    searchPayments: "Поиск платежей...",
    searchWithdrawals: "Поиск заявок...",
    searchTariffs: "Поиск тарифов...",
    searchNotifications: "Поиск уведомлений...",
    searchResults: "Результаты поиска",
    noSearchResults: "Результаты поиска не найдены",
    clearSearch: "Очистить поиск",
    apply: "Применить",
    reset: "Сбросить",
    close: "Закрыть",
    open: "Открыть",
    more: "Больше",
    less: "Меньше",
    all: "Все",
    none: "Ничего",
    yes: "Да",
    no: "Нет",
    on: "Включено",
    off: "Выключено",
    enabled: "Включено",
    disabled: "Отключено",
    auto: "Авто",
    manual: "Вручную",
    default: "По умолчанию",
    custom: "Пользовательский",
    basic: "Базовый",
    advanced: "Расширенный",
    simple: "Простой",
    complex: "Сложный",
    small: "Маленький",
    medium: "Средний",
    large: "Большой",
    today: "Сегодня",
    yesterday: "Вчера",
    thisWeek: "На этой неделе",
    lastWeek: "На прошлой неделе",
    thisMonth: "В этом месяце",
    lastMonth: "В прошлом месяце",
    thisYear: "В этом году",
    lastYear: "В прошлом году",
    dateRange: "Диапазон дат",
    startDate: "Дата начала",
    endDate: "Дата окончания",
    from: "от",
    to: "до",
    clear: "Очистить",
    saveChanges: "Сохранить изменения",
    discard: "Отменить",
    discardChanges: "Отменить изменения",
    confirmDiscard: "Вы уверены, что хотите отменить изменения?",
    confirmDelete: "Вы уверены, что хотите удалить?",
    confirmDeleteMessage: "Это действие необратимо.",
    confirmAction: "Подтвердить действие?",
    confirmActionMessage: "Это действие необратимо.",
    confirmCancel: "Вы уверены, что хотите отменить?",
    confirmCancelMessage: "Все изменения будут потеряны.",
    confirmSave: "Подтвердить сохранение?",
    confirmSaveMessage: "Все изменения будут сохранены.",
    confirmLogout: "Вы уверены, что хотите выйти?",
    confirmLogoutMessage: "Вы собираетесь выйти из системы?",
    confirmReset: "Подтвердить сброс?",
    confirmResetMessage: "Все настройки будут сброшены по умолчанию.",
    confirmSubmit: "Подтвердить отправку?",
    confirmSubmitMessage: "Данные будут отправлены.",
    confirmClose: "Подтвердить закрытие?",
    confirmCloseMessage: "Все изменения будут потеряны.",
    confirmExit: "Подтвердить выход?",
    confirmExitMessage: "Все изменения будут потеряны.",
    confirmLeave: "Подтвердить выход?",
    confirmLeaveMessage: "Все изменения будут потеряны.",
    view: "Просмотр",
    back: "Назад",
    backToUsers: "Назад к пользователям",
    userNotFound: "Пользователь не найден",
    userNotFoundDescription: "Пользователь с этим ID не найден",
    exportUserData: "Экспорт данных пользователя",
    activitySummary: "Сводка активности",
    lastLogin: "Последний вход",
    totalLogins: "Всего входов",
    totalPayments: "Всего платежей",
    totalWithdrawals: "Всего выводов",
    totalSpent: "Всего потрачено",
    totalWithdrawn: "Всего выведено",
    activitySummaryDescription:
      "Здесь вы можете увидеть последние действия пользователя.",
    loginHistory: "История входов",
    paymentHistory: "История платежей",
    paymentHistoryDescription: "История платежей пользователя",
    withdrawalHistory: "История выводов",
    subscriptionPlan: "План подписки",
    subscriptionStatus: "Статус подписки",
    subscriptionStart: "Дата начала подписки",
    subscriptionEnd: "Дата окончания подписки",
    renewSubscription: "Продлить подписку",
    upgradePlan: "Обновить план",
    downgradePlan: "Понизить план",
    cancelSubscription: "Отменить подписку",
    subscriptionCancelled: "Подписка отменена",
    subscriptionActive: "Подписка активна",
    subscriptionExpired: "Подписка истекла",
    subscriptionPending: "Подписка в ожидании",
    profile: "Профиль",
    editProfile: "Редактировать профиль",
    changePassword: "Изменить пароль",
    currentPassword: "Текущий пароль",
    updatePassword: "Обновить пароль",
    profileUpdated: "Профиль обновлён",
    passwordUpdated: "Пароль обновлён",
    incorrectCurrentPassword: "Неверный текущий пароль",
    profilePicture: "Фото профиля",
    uploadNewPhoto: "Загрузить новое фото",
    removePhoto: "Удалить фото",
    photoUpdated: "Фото обновлено",
    photoRemoved: "Фото удалено",
    securitySettings: "Настройки безопасности",
    notificationPreferences: "Настройки уведомлений",
    languagePreferences: "Настройки языка",
    accountSettings: "Настройки аккаунта",
    deleteAccount: "Удалить аккаунт",
    accountDeleted: "Аккаунт удалён",
    accountDeletionWarning:
      "Это действие необратимо. Все данные будут удалены.",
    contactSupport: "Связаться с поддержкой",
    helpCenter: "Центр поддержки",
    faq: "Часто задаваемые вопросы",
    termsAndConditions: "Условия и положения",
    privacyPolicy: "Политика конфиденциальности",
    version: "Версия",
    lastUpdated: "Последнее обновление",
    copyright: "Авторские права",
  },

  kz: {
    dashboard: "Бақылау тақтасы",
    users: "Пайдаланушылар",
    payments: "Төлемдер",
    withdrawals: "Шығарулар",
    tariffs: "Тарифтер",
    statistics: "Статистика",
    notifications: "Хабарламалар",
    settings: "Баптаулар",
    logout: "Шығу",
    darkMode: "Қараңғы режим",
    lightMode: "Жарық режим",
    export: "Экспорттау",
    add: "Қосу",
    edit: "Өңдеу",
    delete: "Жою",
    save: "Сақтау",
    cancel: "Бас тарту",
    confirm: "Растау",
    status: "Күй",
    active: "Белсенді",
    inactive: "Белсенді емес",
    name: "Аты",
    phone: "Телефон",
    email: "Электрондық пошта",
    price: "Баға",
    description: "Сипаттама",
    features: "Ерекшеліктер",
    actions: "Әрекеттер",
    date: "Күні",
    amount: "Сома",
    balance: "Баланс",
    cardNumber: "Карта нөмірі",
    process: "Өңдеу",
    reject: "Қабылдамау",
    pending: "Күтілуде",
    processed: "Өңделді",
    rejected: "Қабылданбады",
    title: "Тақырып",
    message: "Хабарлама",
    recipient: "Алушы",
    send: "Жіберу",
    allUsers: "Барлық пайдаланушылар",
    premiumUsers: "Премиум пайдаланушылар",
    standardUsers: "Стандартты пайдаланушылар",
    basicUsers: "Негізгі пайдаланушылар",
    general: "Жалпы",
    appearance: "Көрініс",
    security: "Қауіпсіздік",
    language: "Тіл",
    dateFormat: "Күн форматы",
    emailNotifications: "Электрондық пошта хабарламалары",
    smsNotifications: "SMS хабарламалары",
    pushNotifications: "Push хабарламалары",
    twoFactorAuth: "Екі факторлы аутентификация",
    sessionTimeout: "Сессия уақытының аяқталуы",
    passwordPolicy: "Құпиясөз саясаты",
    minLength: "Минималды ұзындық",
    requireUppercase: "Үлкен әріп қажет",
    requireNumbers: "Сандар қажет",
    requireSpecialChars: "Арнайы таңбалар қажет",
    siteName: "Сайт атауы",
    siteDescription: "Сайт сипаттамасы",
    contactEmail: "Байланыс электрондық поштасы",
    supportPhone: "Қолдау телефоны",
    theme: "Тақырып",
    dark: "Қараңғы",
    light: "Жарық",
    system: "Жүйе",
    login: "Кіру",
    password: "Құпиясөз",
    forgotPassword: "Құпиясөзді ұмыттыңыз ба?",
    resetPassword: "Құпиясөзді қалпына келтіру",
    sendCode: "Код жіберу",
    verifyCode: "Кодты тексеру",
    newPassword: "Жаңа құпиясөз",
    confirmPassword: "Құпиясөзді растау",
    resetPasswordDescription:
      "Құпиясөзді қалпына келтіру үшін телефон нөміріңізді енгізіңіз",
    codeVerificationDescription: "Телефоныңызға жіберілген кодты енгізіңіз",
    newPasswordDescription: "Жаңа құпиясөзіңізді енгізіңіз",
    invalidCredentials: "Қате электрондық пошта немесе құпиясөз",
    invalidCode: "Қате код",
    passwordsDontMatch: "Құпиясөздер сәйкес келмейді",
    passwordResetSuccess: "Құпиясөз сәтті қалпына келтірілді",
    loginWithGoogle: "Google арқылы кіру",
    or: "Немесе",
    totalUsers: "Жалпы пайдаланушылар",
    totalRevenue: "Жалпы табыс",
    activeTariffs: "Белсенді тарифтер",
    pendingWithdrawals: "Күтілуде тұрған шығарулар",
    recentPayments: "Соңғы төлемдер",
    newUsers: "Жаңа пайдаланушылар",
    userDetails: "Пайдаланушы мәліметтері",
    tariffDetails: "Тариф мәліметтері",
    notificationDetails: "Хабарлама мәліметтері",
    withdrawalDetails: "Шығару мәліметтері",
    paymentDetails: "Төлем мәліметтері",
    overview: "Шолу",
    analytics: "Аналитика",
    userActivity: "Пайдаланушы белсенділігі",
    revenueStatistics: "Табыс статистикасы",
    tariffDistribution: "Тарифтер таралуы",
    withdrawalStatistics: "Шығарулар статистикасы",
    paymentStatistics: "Төлемдер статистикасы",
    logins: "Кірулер",
    transactions: "Транзакциялар",
    downloadPDF: "PDF жүктеу",
    downloadCSV: "CSV жүктеу",
    downloadExcel: "Excel жүктеу",
    print: "Басып шығару",
    noDataFound: "Деректер табылмады",
    loading: "Жүктелуде...",
    error: "Қате",
    success: "Сәтті",
    warning: "Ескерту",
    info: "Ақпарат",
    previous: "Алдыңғы",
    next: "Келесі",
    page: "Бет",
    of: "ішінен",
    itemsPerPage: "Беттегі элементтер саны",
    showingItemsOf: "{start} - {end} элементтерінен {total} көрсетілуде",
    filter: "Сүзгі",
    sort: "Сұрыптау",
    ascending: "Өсу реті",
    descending: "Кему реті",
    clearFilters: "Сүзгілерді тазарту",
    applyFilters: "Сүзгілерді қолдану",
    selectAll: "Барлығын таңдау",
    deselectAll: "Барлығын таңдамау",
    select: "Таңдау",
    selected: "Таңдалған",
    items: "Элементтер",
    item: "Элемент",
    noItemsSelected: "Элементтер таңдалмады",
    allItemsSelected: "Барлық элементтер таңдалды",
    search: "Іздеу",
    searchUsers: "Пайдаланушыларды іздеу...",
    searchPayments: "Төлемдерді іздеу...",
    searchWithdrawals: "Шығаруларды іздеу...",
    searchTariffs: "Тарифтерді іздеу...",
    searchNotifications: "Хабарламаларды іздеу...",
    searchResults: "Іздеу нәтижелері",
    noSearchResults: "Іздеу нәтижелері табылмады",
    clearSearch: "Іздеуді тазарту",
    apply: "Қолдану",
    reset: "Қалпына келтіру",
    close: "Жабу",
    open: "Ашу",
    more: "Көбірек",
    less: "Аз",
    all: "Барлығы",
    none: "Ешқайсысы",
    yes: "Иә",
    no: "Жоқ",
    on: "Қосулы",
    off: "Сөндірулі",
    enabled: "Қосылған",
    disabled: "Сөндірілген",
    auto: "Авто",
    manual: "Қолмен",
    default: "Әдепкі",
    custom: "Бапталған",
    basic: "Негізгі",
    advanced: "Кеңейтілген",
    simple: "Қарапайым",
    complex: "Күрделі",
    small: "Кіші",
    medium: "Орташа",
    large: "Үлкен",
    today: "Бүгін",
    yesterday: "Кеше",
    thisWeek: "Осы апта",
    lastWeek: "Өткен апта",
    thisMonth: "Осы ай",
    lastMonth: "Өткен ай",
    thisYear: "Осы жыл",
    lastYear: "Өткен жыл",
    dateRange: "Күн ауқымы",
    startDate: "Басталу күні",
    endDate: "Аяқталу күні",
    from: "Бастап",
    to: "Дейін",
    clear: "Тазарту",
    saveChanges: "Өзгерістерді сақтау",
    discard: "Бас тарту",
    discardChanges: "Өзгерістерден бас тарту",
    confirmDiscard: "Өзгерістерден бас тартқыңыз келетініне сенімдісіз бе?",
    confirmDelete: "Жоюға сенімдісіз бе?",
    confirmDeleteMessage: "Бұл әрекет қайтарылмайды.",
    confirmAction: "Бұл әрекетті орындауға сенімдісіз бе?",
    confirmActionMessage: "Бұл әрекет қайтарылмайды.",
    confirmCancel: "Бас тартуға сенімдісіз бе?",
    confirmCancelMessage: "Барлық өзгерістер жоғалады.",
    confirmSave: "Сақтағыңыз келетініне сенімдісіз бе?",
    confirmSaveMessage: "Барлық өзгерістер сақталады.",
    confirmLogout: "Шығуды қалайсыз ба?",
    confirmLogoutMessage: "Сіз жүйеден шығасыз.",
    confirmReset: "Қалпына келтіруді қалайсыз ба?",
    confirmResetMessage: "Барлық баптаулар әдепкі мәнге қайтарылады.",
    confirmSubmit: "Жібергіңіз келетініне сенімдісіз бе?",
    confirmSubmitMessage: "Деректер жіберіледі.",
    confirmClose: "Жабуды қалайсыз ба?",
    confirmCloseMessage: "Барлық өзгерістер жойылады.",
    confirmExit: "Шығуды қалайсыз ба?",
    confirmExitMessage: "Барлық өзгерістер жойылады.",
    confirmLeave: "Шығуды қалайсыз ба?",
    confirmLeaveMessage: "Барлық өзгерістер жойылады.",
    view: "Көру",
    back: "Артқа",
    backToUsers: "Пайдаланушыларға оралу",
    userNotFound: "Пайдаланушы табылмады",
    userNotFoundDescription: "Осы ID-мен пайдаланушы табылмады",
    exportUserData: "Пайдаланушы деректерін экспорттау",
    activitySummary: "Белсенділік қорытындысы",
    activitySummaryDescription: "Пайдаланушы белсенділігі туралы қорытынды",
    lastLogin: "Соңғы кіру",
    totalLogins: "Жалпы кірулер",
    totalPayments: "Жалпы төлемдер",
    totalWithdrawals: "Жалпы алу сомасы",
    totalSpent: "Жалпы шығын",
    totalWithdrawn: "Жалпы алынған сома",
    paymentHistory: "Төлем тарихы",
    paymentHistoryDescription: "Пайдаланушының төлем тарихы",
    withdrawalHistory: "Алу тарихы",
    withdrawalHistoryDescription: "Пайдаланушының алу тарихы",
    noPaymentsFound: "Төлемдер табылмады",
    noWithdrawalsFound: "Алу жазбалары табылмады",
    id: "ID",
    registrationDate: "Тіркелу күні",
    openMenu: "Мәзірді ашу",
    generalSettings: "Жалпы баптаулар",
    appearanceSettings: "Көрініс баптаулары",
    notificationSettings: "Хабарландыру баптаулары",
    securitySettings: "Қауіпсіздік баптаулары",
    selectTheme: "Тақырыпты таңдаңыз",
    selectLanguage: "Тілді таңдаңыз",
    selectDateFormat: "Күн пішімін таңдаңыз",
    usersDescription: "Платформада тіркелген барлық пайдаланушылар тізімі",
    allPayments: "Барлық төлемдер",
    paymentsDescription: "Платформада жасалған барлық төлемдер тізімі",
    allWithdrawals: "Барлық алу операциялары",
    withdrawalsDescription: "Пайдаланушылардың жіберген алу сұраныстары",
    allTariffs: "Барлық тарифтер",
    tariffsDescription: "Платформада қолжетімді барлық тарифтер тізімі",
    newNotification: "Жаңа хабарлама",
    sentNotifications: "Жіберілген хабарламалар",
    notificationTitle: "Хабарлама тақырыбы",
    notificationMessage: "Хабарлама мәтіні",
    selectRecipient: "Алушыны таңдаңыз",
    recipientDescription: "Хабарлама алушысын таңдаңыз",
    column: "Бағана",
    markAllAsRead: "Барлығын оқылды деп белгілеу",
    noNotifications: "Хабарламалар жоқ",
    newNotificationMessage: "Сізде жаңа хабарлама бар. Тексеріңіз.",
    editUserDescription: "Пайдаланушы мәліметтерін өзгерту",
    selectTariff: "Тарифті таңдаңыз",
    deactivate: "Бұғаттау",
    activate: "Белсендіру",
    comparedToLastMonth: "өткен аймен салыстырғанда",
    allTime: "Барлық уақыт",
    currentlyActiveTariffs: "Қазір белсенді тарифтер",
    withdrawalRequests: "Алу сұраныстары",
    userActivityDescription: "Пайдаланушы белсенділігі туралы ақпарат",
    paymentStatisticsDescription: "Төлем статистикасы туралы ақпарат",
    withdrawalStatisticsDescription: "Алу статистикасы туралы ақпарат",
    analyticsNotAvailable: "Аналитика деректері әлі қолжетімді емес",
    profile: "Профиль",
    profileInformation: "Профиль ақпараты",
    updateYourProfileInformation: "Профиль ақпаратыңызды жаңартыңыз",
    changePassword: "Құпиясөзді өзгерту",
    updateYourPassword: "Құпиясөзіңізді жаңартыңыз",
    currentPassword: "Қазіргі құпиясөз",
    profileUpdated: "Профиль жаңартылды",
    profileUpdatedDescription: "Профиль ақпаратыңыз сәтті жаңартылды",
    passwordUpdated: "Құпиясөз жаңартылды",
    passwordUpdatedDescription: "Құпиясөзіңіз сәтті жаңартылды",
  },
  kg: {
    dashboard: "Борбордук панель",
    users: "Колдонуучулар",
    payments: "Төлемдер",
    withdrawals: "Чыгарымдар",
    tariffs: "Тарифтер",
    statistics: "Статистика",
    notifications: "Эскертмелер",
    settings: "Жөндөөлөр",
    logout: "Чыгуу",
    darkMode: "Караңгылыктуу режим",
    lightMode: "Жарык режим",
    export: "Экспорттоо",
    add: "Кошуу",
    edit: "Түзөтүү",
    delete: "Өчүрүү",
    save: "Сактоо",
    cancel: "Жокко чыгаруу",
    confirm: "Тастыктоо",
    status: "Статус",
    active: "Активдүү",
    inactive: "Активдүү эмес",
    name: "Аты",
    phone: "Телефон",
    email: "Электрондук почта",
    price: "Баасы",
    description: "Тасвирлама",
    features: "Өзгөчөлүктөр",
    actions: "Чаралар",
    date: "Дата",
    amount: "Саны",
    balance: "Баланска",
    cardNumber: "Карта номери",
    process: "Процесс",
    reject: "Чечмей коюу",
    pending: "Күтүүдө",
    processed: "Өткөн",
    rejected: "Чечилген эмес",
    title: "Тема",
    message: "Хабар",
    recipient: "Алуучу",
    send: "Жөнөтүү",
    allUsers: "Бардык колдонуучулар",
    premiumUsers: "Премиум колдонуучулар",
    standardUsers: "Стандарттык колдонуучулар",
    basicUsers: "Негизги колдонуучулар",
    general: "Жалпы",
    appearance: "Көрүнүш",
    security: "Коопсуздук",
    language: "Тил",
    dateFormat: "Дата форматы",
    emailNotifications: "Электрондук почта аркылуу эскертмелер",
    smsNotifications: "SMS аркылуу эскертмелер",
    pushNotifications: "Push аркылуу эскертмелер",
    twoFactorAuth: "Эки факторлуу аутентификация",
    sessionTimeout: "Сессиянын мөөнөтү",
    passwordPolicy: "Пароль саясаты",
    minLength: "Минималдуу узундук",
    requireUppercase: "Жогорку катарды талап кылуу",
    requireNumbers: "Сандарды талап кылуу",
    requireSpecialChars: "Арнайы белгілерди талап кылуу",
    siteName: "Сайттын аты",
    siteDescription: "Сайттын тасвирламасы",
    contactEmail: "Байланыш электрондук почтасы",
    supportPhone: "Колдоо телефону",
    theme: "Теманы тандоо",
    dark: "Караңгы",
    light: "Жарык",
    system: "Жүйө",
    login: "Кирүү",
    password: "Пароль",
    forgotPassword: "Паролду унуттуңузбу?",
    resetPassword: "Парольду калыбына келтирүү",
    sendCode: "Кодду жөнөтүү",
    verifyCode: "Кодду текшерүү",
    newPassword: "Жаңы пароль",
    confirmPassword: "Парольду тактоо",
    resetPasswordDescription:
      "Парольду калыбына келтирүү үчүн телефон номериңизди киргизиңиз",
    codeVerificationDescription: "Телефонуңузга жөнөтүлгөн кодду киргизиңиз",
    newPasswordDescription: "Жаңы паролду киргизиңиз",
    invalidCredentials: "Жараксыз электрондук почта же пароль",
    invalidCode: "Жараксыз код",
    passwordsDontMatch: "Парольдер дал келбейт",
    passwordResetSuccess: "Пароль ийгиликтүү калыбына келтирилди",
    loginWithGoogle: "Google менен кирүү",
    or: "Же",
    totalUsers: "Жалпы колдонуучулар",
    totalRevenue: "Жалпы кирешелер",
    activeTariffs: "Активдүү тарифтер",
    pendingWithdrawals: "Күтүп жаткан чыгарымдар",
    recentPayments: "Жакындагы төлөмдөр",
    newUsers: "Жаңы колдонуучулар",
    userDetails: "Колдонуучу маалыматы",
    tariffDetails: "Тарифтин деталдары",
    notificationDetails: "Эскертменин деталдары",
    withdrawalDetails: "Чыгарымдын деталдары",
    paymentDetails: "Төлөмдүн деталдары",
    overview: "Карап чыгуу",
    analytics: "Аналитика",
    userActivity: "Колдонуучу активдүүлүгү",
    revenueStatistics: "Киреше статистикасы",
    tariffDistribution: "Тариф таратуу",
    withdrawalStatistics: "Чыгарымдар статистикасы",
    paymentStatistics: "Төлөм статистикасы",
    logins: "Кирүүлөр",
    transactions: "Транзакциялар",
    downloadPDF: "PDF жүктөө",
    downloadCSV: "CSV жүктөө",
    downloadExcel: "Excel жүктөө",
    print: "Басып чыгарыңыз",
    noDataFound: "Маалымат табылган жок",
    loading: "Жүктөлүүдө...",
    error: "Ката",
    success: "Ийгиликтүү",
    warning: "Эскертүү",
    info: "Маалымат",
    previous: "Мурунку",
    next: "Кийинки",
    page: "Баракча",
    of: "ден",
    itemsPerPage: "Баракча боюнча элементтер",
    showingItemsOf: "{start} ден {end} чейин {total} элемент көрсөтүлүүдө",
    filter: "Фильтр",
    sort: "Сорттоо",
    ascending: "Жогорулатуу",
    descending: "Төмөндөтүү",
    clearFilters: "Фильтрлерди тазалоо",
    applyFilters: "Фильтрлерди колдонуу",
    selectAll: "Бардыгын тандоо",
    deselectAll: "Бардыгын тандоо жок",
    select: "Тандоо",
    selected: "Тандалды",
    items: "Элементтер",
    item: "Элемент",
    noItemsSelected: "Элементтер тандалган жок",
    allItemsSelected: "Бардык элементтер тандалды",
    search: "Издөө",
    searchUsers: "Колдонуучуларды издөө...",
    searchPayments: "Төлөмдөрдү издөө...",
    searchWithdrawals: "Чыгарымдарды издөө...",
    searchTariffs: "Тарифтерди издөө...",
    searchNotifications: "Эскертмелерди издөө...",
    searchResults: "Издөө натыйжалары",
    noSearchResults: "Издөө натыйжалары табылган жок",
    clearSearch: "Издөө тазалоо",
    apply: "Колдонуу",
    reset: "Калыбына келтирүү",
    close: "Жабуу",
    open: "Ачууну",
    more: "Көбүрөөк",
    less: "Аз",
    all: "Бардык",
    none: "Эч кандай",
    yes: "Ооба",
    no: "Жок",
    on: "Жөндөөдө",
    off: "Өчүрүү",
    enabled: "Иштетүүдө",
    disabled: "Өчүрүлдү",
    auto: "Автоматтык",
    manual: "Кол менен",
    default: "Боштук",
    custom: "Бейтап",
    basic: "Негизги",
    advanced: "Ийгиликтүү",
    simple: "Жөнөкөй",
    complex: "Комплекс",
    small: "Кичине",
    medium: "Орто",
    large: "Чоң",
    today: "Бүгүн",
    yesterday: "Кечээ",
    thisWeek: "Бул апта",
    lastWeek: "Өткөн апта",
    thisMonth: "Бул ай",
    lastMonth: "Өткөн ай",
    thisYear: "Бул жыл",
    lastYear: "Өткөн жыл",
    dateRange: "Дата аралыгы",
    startDate: "Башталгыч дата",
    endDate: "Аяктоо дата",
    from: "Башталгычтан",
    to: "Качан",
    clear: "Тазалоо",
    saveChanges: "Өзгөртүүлөрдү сактоо",
    discard: "Жокко чыгаруу",
    discardChanges: "Өзгөртүүлөрдү жокко чыгаруу",
    confirmDiscard: "Өзгөртүүлөрдү жокко чыгаруу үчүн ишенесизби?",
    confirmDelete: "Өчүрүүнү ишендиресизби?",
    confirmDeleteMessage: "Бул иш аракет кайтарылып алынбайт.",
    confirmAction: "Бул иш аракетти аткарууга ишенесизби?",
    confirmActionMessage: "Бул иш аракет кайтарылып алынбайт.",
    confirmCancel: "Жокко чыгарууну ишенесизби?",
    confirmCancelMessage: "Бардык өзгөртүүлөр жоголушу мүмкүн.",
    confirmSave: "Сактоо үчүн ишенесизби?",
    confirmSaveMessage: "Бардык өзгөртүүлөр сакталат.",
    confirmLogout: "Чыгуу үчүн ишенесизби?",
    confirmLogoutMessage: "Жүйөдөн чыгасыз.",
    confirmReset: "Калыбына келтирүүнү ишенесизби?",
    confirmResetMessage: "Бардык орнотуулар баштапкы абалга кайтарылат.",
    confirmSubmit: "Жөнөтүүнү ишенесизби?",
    confirmSubmitMessage: "Маалымат жөнөтүлөт.",
    confirmClose: "Жабууну ишенесизби?",
    confirmCloseMessage: "Бардык өзгөртүүлөр жоголушу мүмкүн.",
    confirmExit: "Чыгуу үчүн ишенесизби?",
    confirmExitMessage: "Бардык өзгөртүүлөр жоголушу мүмкүн.",
    confirmLeave: "Таштап кетүүнү ишенесизби?",
    confirmLeaveMessage: "Бардык өзгөртүүлөр жоголушу мүмкүн.",
    view: "Карап чыгуу",
    back: "Арка",
    backToUsers: "Колдонуучуларга кайтуу",
    userNotFound: "Колдонуучу табылган жок",
    userNotFoundDescription: "Бул ID менен колдонуучу табылган жок",
    exportUserData: "Колдонуучу маалыматтарын экспорттоо",
    activitySummary: "Активдүүлүк жыйынтыгы",
    activitySummaryDescription: "Колдонуучу активдүүлүгүнүн жыйынтыгы",
    lastLogin: "Акыркы кирүү",
    totalLogins: "Жалпы кирүүлөр",
    totalPayments: "Жалпы төлөмдөр",
    totalWithdrawals: "Жалпы чыгаруулар",
    totalSpent: "Жалпы сарпталган",
    totalWithdrawn: "Жалпы чыгарылган",
    paymentHistory: "Төлөм тарыхы",
    paymentHistoryDescription: "Колдонуучунун төлөм тарыхы",
    withdrawalHistory: "Акча чыгарып алуу тарыхы",
    withdrawalHistoryDescription: "Колдонуучунун акча чыгарып алуу тарыхы",
    noPaymentsFound: "Төлөмдөр табылган жок",
    noWithdrawalsFound: "Акча чыгарып алуу жазуулары табылган жок",
    id: "ID",
    registrationDate: "Катталуу күнү",
    openMenu: "Менюну ачуу",
    generalSettings: "Жалпы жөндөөлөр",
    appearanceSettings: "Тышкы көрүнүш жөндөөлөрү",
    notificationSettings: "Хабарландыруу жөндөөлөрү",
    securitySettings: "Коопсуздук жөндөөлөрү",
    selectTheme: "Тематиканы тандаңыз",
    selectLanguage: "Тилди тандаңыз",
    selectDateFormat: "Күндүн форматын тандаңыз",
    usersDescription: "Платформада катталган бардык колдонуучулардын тизмеси",
    allPayments: "Бардык төлөмдөр",
    paymentsDescription: "Платформада жасалган бардык төлөмдөрдүн тизмеси",
    allWithdrawals: "Бардык акча чыгарып алуулар",
    withdrawalsDescription: "Колдонуучулардын акча чыгарып алуу суранычтары",
    allTariffs: "Бардык тарифтер",
    tariffsDescription:
      "Платформада жеткиликтүү болгон бардык тарифтердин тизмеси",
    newNotification: "Жаңы билдирүү",
    sentNotifications: "Жөнөтүлгөн билдирүүлөр",
    notificationTitle: "Билдирүүнүн аталышы",
    notificationMessage: "Билдирүүнүн мазмуну",
    selectRecipient: "Алушуну тандаңыз",
    recipientDescription: "Билдирүү алгысы келген адамды тандаңыз",
    column: "Багана",
    markAllAsRead: "Бардыгын окулган деп белгилөө",
    noNotifications: "Билдирүүлөр жок",
    newNotificationMessage: "Жаңы билдирүү бар. Текшерип көрүңүз.",
    editUserDescription: "Колдонуучунун маалыматын өзгөртүү",
    selectTariff: "Тарифти тандаңыз",
    deactivate: "Жабуу",
    activate: "Иштетүү",
    comparedToLastMonth: "өткөн ай менен салыштырганда",
    allTime: "Бардык убакыт",
    currentlyActiveTariffs: "Азыркы учурдагы иштөө тарифтери",
    withdrawalRequests: "Акча чыгарып алуу суранычтары",
    userActivityDescription: "Колдонуучунун активдүүлүгү тууралуу маалымат",
    paymentStatisticsDescription: "Төлөм статистикасы жөнүндө маалымат",
    withdrawalStatisticsDescription:
      "Акча чыгарып алуу статистикасы жөнүндө маалымат",
    analyticsNotAvailable: "Аналитика маалыматтары азырынча жеткиликтүү эмес",
    profile: "Профиль",
    profileInformation: "Профиль маалыматы",
    updateYourProfileInformation: "Профиль маалыматыңызды жаңыртыңыз",
    changePassword: "Жупаш сөздү өзгөртүү",
    updateYourPassword: "Жупаш сөздү жаңыртыңыз",
    currentPassword: "Азыркы жупаш сөз",
    profileUpdated: "Профиль жаңыртылды",
    profileUpdatedDescription: "Профиль маалыматыңыз ийгиликтүү жаңыртылды",
    passwordUpdated: "Жупаш сөз жаңыртылды",
    passwordUpdatedDescription: "Жупаш сөөгүңүз ийгиликтүү жаңыртылды",
  },

  tj: {
    dashboard: "Дошборд",
    users: "Пайдокунандагон",
    payments: "Пулпартоӣ",
    withdrawals: "Пултозӣ",
    tariffs: "Тарифҳо",
    statistics: "Статистика",
    notifications: "Огоҳиномаҳо",
    settings: "Танзимот",
    logout: "Хуруҷ",
    darkMode: "Режими торик",
    lightMode: "Режими равшан",
    export: "Содирот",
    add: "Илова кардан",
    edit: "Таҳрир кардан",
    delete: "Махфӣ кардан",
    save: "Захира кардан",
    cancel: "Бекор кардан",
    confirm: "Тасдиқ кардан",
    status: "Статус",
    active: "Фаъол",
    inactive: "Нафаъол",
    name: "Ном",
    phone: "Телефон",
    email: "Почтаи электронӣ",
    price: "Нарх",
    description: "Тавсиф",
    features: "Хусусиятҳо",
    actions: "Амалиёт",
    date: "Таърих",
    amount: "Миқдор",
    balance: "Тавозун",
    cardNumber: "Рақами корти",
    process: "Раванд",
    reject: "Рад кардан",
    pending: "Мўҳлати интизорӣ",
    processed: "Пурсида шудааст",
    rejected: "Рад карда шудааст",
    title: "Сарлавҳа",
    message: "Паём",
    recipient: "Гирифанда",
    send: "Ирсол кардан",
    allUsers: "Ҳамаи пайвандшудагон",
    premiumUsers: "Пайдокунандагони премиум",
    standardUsers: "Пайдокунандагони стандартӣ",
    basicUsers: "Пайдокунандагони асосӣ",
    general: "Умумӣ",
    appearance: "Зоҳир",
    security: "Амният",
    language: "Забон",
    dateFormat: "Шакли таърих",
    emailNotifications: "Огоҳиномаҳои почтаи электронӣ",
    smsNotifications: "Огоҳиномаҳои SMS",
    pushNotifications: "Огоҳиномаҳои пушт",
    twoFactorAuth: "Тасдиқи дугона",
    sessionTimeout: "Вақти барои мӯҳлати муҳити",
    passwordPolicy: "Сиёсати парол",
    minLength: "Минімум дарозӣ",
    requireUppercase: "Ҳатман хатҳои калон",
    requireNumbers: "Ҳатман рақамҳо",
    requireSpecialChars: "Ҳатман рамзҳои махсус",
    siteName: "Номи вебсайт",
    siteDescription: "Тавсифи вебсайт",
    contactEmail: "Почтаи электронӣ барои тамос",
    supportPhone: "Телефони хидматрасонӣ",
    theme: "Мавзӯъ",
    dark: "Торик",
    light: "Равшан",
    system: "Систем",
    login: "Вуруд",
    password: "Парол",
    forgotPassword: "Пароли худро фаромӯш кардед?",
    resetPassword: "Тавзеҳ кардани парол",
    sendCode: "Фаристодан код",
    verifyCode: "Тасдиқи код",
    newPassword: "Пароли нав",
    confirmPassword: "Тасдиқи парол",
    resetPasswordDescription:
      "Барои тағйир додани парол, рақами телефони худро ворид кунед",
    codeVerificationDescription: "Коди фиристодашударо ворид кунед",
    newPasswordDescription: "Пароли навро ворид кунед",
    invalidCredentials: "Рақами почта ё парол дуруст нест",
    invalidCode: "Код нодуруст аст",
    passwordsDontMatch: "Паролҳо якхела нестанд",
    passwordResetSuccess: "Парол бо муваффақият тағйир ёфт",
    loginWithGoogle: "Вуруд бо Google",
    or: "Ё",
    totalUsers: "Ҳаммаи пайвандшудагон",
    totalRevenue: "Ҳаммаи даромад",
    activeTariffs: "Тарифҳои фаъол",
    pendingWithdrawals: "Пултозии интизорӣ",
    recentPayments: "Пулпартоӣ нав",
    newUsers: "Пайдокунандагони нав",
    userDetails: "Маълумоти корбар",
    tariffDetails: "Маълумоти тариф",
    notificationDetails: "Маълумоти огоҳинома",
    withdrawalDetails: "Маълумоти пултозӣ",
    paymentDetails: "Маълумоти пулпартоӣ",
    overview: "Маълумотҳои умумӣ",
    analytics: "Аналитика",
    userActivity: "Фаъолияти корбар",
    revenueStatistics: "Статистикаи даромад",
    tariffDistribution: "Тақсимоти тариф",
    withdrawalStatistics: "Статистикаи пултозӣ",
    paymentStatistics: "Статистикаи пулпартоӣ",
    logins: "Вурудҳо",
    transactions: "Амалиёт",
    downloadPDF: "Насб кардани PDF",
    downloadCSV: "Насб кардани CSV",
    downloadExcel: "Насб кардани Excel",
    print: "Чоп кардан",
    noDataFound: "Маълумот ёфта нашуд",
    loading: "Ҳоло боркунӣ...",
    error: "Хато",
    success: "Муффақият",
    warning: "Огоҳӣ",
    info: "Маълумот",
    previous: "Камтар",
    next: "Баъд",
    page: "Саҳифа",
    of: "аз",
    itemsPerPage: "Миқдор дар саҳифа",
    showingItemsOf: "Намоиши {start} то {end} аз {total} предметҳо",
    filter: "Ҳадаф",
    sort: "Тартиб додан",
    ascending: "Баробаркунӣ",
    descending: "Камшавӣ",
    clearFilters: "Танзимотро тоза кунед",
    applyFilters: "Танзимотро дароз кунед",
    selectAll: "Ҳамаи баҳоро интихоб кунед",
    deselectAll: "Ҳамаи баҳоро бекор кунед",
    select: "Интихоб кардан",
    selected: "Интихобшуда",
    items: "Моҳа",
    item: "Моҳа",
    noItemsSelected: "Ҳеҷ чиз интихоб нашуд",
    allItemsSelected: "Ҳама чиз интихоб карда шудааст",
    search: "Ҷустуҷӯ",
    searchUsers: "Пайдо кардани пайвандкунандагон...",
    searchPayments: "Пулпартоӣ ҷустуҷӯ...",
    searchWithdrawals: "Пултозӣ ҷустуҷӯ...",
    searchTariffs: "Тарифҳо ҷустуҷӯ...",
    searchNotifications: "Огоҳинома ҷустуҷӯ...",
    searchResults: "Натиҷаҳои ҷустуҷӯ",
    noSearchResults: "Натиҷаҳои ҷустуҷӯ ёфта нашуд",
    clearSearch: "Ҷустуҷӯро тоза кунед",
    apply: "Илова кардан",
    reset: "Барқарор кардан",
    close: "Пӯшида",
    open: "Гирёфтан",
    more: "Бештар",
    less: "Камтар",
    all: "Ҳама",
    none: "Ҳеҷ",
    yes: "Бале",
    no: "Не",
    on: "Дар",
    off: "Барнома нест",
    enabled: "Фаъол",
    disabled: "Намебуд",
    auto: "Авто",
    manual: "Дастӣ",
    default: "Пешфарз",
    custom: "Шахсӣ",
    basic: "Асосӣ",
    advanced: "Равшан",
    simple: "Содда",
    complex: "Мураккаб",
    small: "Кичик",
    medium: "Миёна",
    large: "Васеъ",
    today: "Имрӯз",
    yesterday: "Дирӯз",
    thisWeek: "Ин ҳафта",
    lastWeek: "Ҳафтаи гузашта",
    thisMonth: "Моҳи мазкур",
    lastMonth: "Моҳи гузашта",
    thisYear: "Соли ҷорӣ",
    lastYear: "Соли гузашта",
    allTime: "Ҳамаи вақт",
    noNotifications: "Ҳеҷ гуна огоҳиномае вуҷуд надорад",
    notificationSent: "Огоҳинома фиристода шуд",
    notificationReceived: "Огоҳинома қабул карда шуд",
    notificationFailed: "Фиристодани огоҳинома номуваффақ шуд",
    markAsRead: "Марк кардан ҳамчун хониш",
    markAsUnread: "Марк кардан ҳамчун хонда нашуд",
    read: "Хонда шуд",
    unread: "Хонда нашуд",
    readAll: "Хондан ҳама",
    unreadAll: "Хондан на ҳама",
    noNotificationsFound: "Ҳеҷ гуна огоҳиномае ёфта нашуд",
    noUsersFound: "Ҳеҷ гуна пайвандкунандае ёфта нашуд",
    noPaymentsFound: "Ҳеҷ гуна пулпартоӣ ёфта нашуд",
    noWithdrawalsFound: "Ҳеҷ гуна пултозӣ ёфта нашуд",
    noTariffsFound: "Ҳеҷ гуна тариф ёфта нашуд",
    noDataAvailable: "Маълумот дастрас нест",
    noResultsFound: "Натиҷаҳо ёфта нашуд",
    noItemsFound: "Моҳа ёфта нашуд",
    noUsers: "Ҳеҷ гуна пайвандкунандае нест",
    noPayments: "Ҳеҷ гуна пулпартоӣ нест",
    noWithdrawals: "Ҳеҷ гуна пултозӣ нест",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("uz");

  useEffect(() => {
    // Load language from localStorage if available
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && Object.keys(translations).includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }

    // Set up event listener for language changes in other tabs
    const handleStorageChange = (e: StorageEvent) => {
      if (
        e.key === "language" &&
        e.newValue &&
        Object.keys(translations).includes(e.newValue as Language)
      ) {
        setLanguage(e.newValue as Language);
      }
    };

    window.addEventListener("storage", handleStorageChange);
    return () => window.removeEventListener("storage", handleStorageChange);
  }, []);

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage);
    localStorage.setItem("language", newLanguage);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ language, setLanguage: handleSetLanguage, t }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
